const mainNavigationRoutes = {
  home: "Home",
  tab_home: "TabHome",
  login: "LogIn",
  forgotPasscode: "ForgotPassCode",
  accountDetails: "AccountDetails",
  findAccount: "FindAccount",
  accountPreview: "AccountPreview",
  settingScreen: "SettingScreen",
  profileScreen: "profileScreen",
  endWorkScreen: "EndWorkScreen",
  changePinScreen: "ChangePinScreen",
  reportDayScreen: "ReportDayScreen",
  reportTypeScreen: "ReportTypeScreen",
  nonCollectionReport: "NonCollectionReport",
  miniStatement: "MiniStatement",
  miniStatementInner: "MiniStatementInner",
  dateWiseCollSummary: "DateWiseCollSummary",
  reportChooseScreen: "ReportChooseScreen",
  printerConnectScreen: "PrinterConnectScreen",
  duplicateReceipt: "DuplicateReceipt",
  duplicateReceiptInner: "DuplicateReceiptInnner",
  notificationScreen: "NotificationScreen",
  aboutScreen: "AboutScreen",
  lastFiveTnxScreen: "LastFiveTnxScreen",
}

export default mainNavigationRoutes
